"""Internal backend-neutral IR for TorchLens capture unification."""

from __future__ import annotations

from .capture_events import (
    CaptureEvents,
    register_live_event,
)
from .container import ContainerSpec
from .container_registry import (
    ContainerLeafOccurrence,
    ContainerRecord,
    ContainerRegistry,
    ContainerSnapshot,
    FuncSite,
    IdentityEntry,
    ModelSite,
    ModuleSite,
    Phase,
    Role,
    WalkResult,
    walk_container,
)
from .events import (
    ArgTemplateRef,
    BackwardPassEnd,
    BackwardPassStart,
    BlobRef,
    BufferWriteEvent,
    ConditionalEvent,
    EdgeUseKind,
    FunctionCallRef,
    GradFnDiscovered,
    GradFnFired,
    InterventionState,
    ModuleEnterEvent,
    ModuleExitEvent,
    ModuleFrame,
    ModulePrepEvent,
    OpEvent,
    OpEventKind,
    OpGradObserved,
    OutputRef,
    OutputVersionEvent,
    ParamGradObserved,
    BackwardCoverageGap,
    InterventionAppliedEvent,
    ParentEdge,
    PreHookProvenanceEvent,
    edge_use_kind,
    is_control_edge_use,
    is_value_edge_use,
)
from .intervention import FireResult, FunctionEventInput, InterventionTemplateRef
from .live_index import LiveIndex, LiveIndexWindowError
from .predicate import (
    MLXValueUnavailableError,
    RecordContext,
    _DEFERRED_VALUE,
    coerce_deferred_value,
    is_deferred_value,
)
from .refs import DeferredRef, DeviceRef, DtypeRef, ParamRef, ReservedLabel, TensorRef
from .semantics import BackendSemantics, CapturePolicy
from .workspaces import (
    LEGACY_TRACE_BUILD_STATE_KEYS,
    ModuleCaptureWorkspace,
    RawGraphWorkspace,
    WrapperRuntimeWorkspace,
)

__all__ = [
    "ArgTemplateRef",
    "BackendSemantics",
    "BackwardPassEnd",
    "BackwardPassStart",
    "BlobRef",
    "BufferWriteEvent",
    "CaptureEvents",
    "CapturePolicy",
    "ConditionalEvent",
    "ContainerSpec",
    "ContainerLeafOccurrence",
    "ContainerRecord",
    "ContainerRegistry",
    "ContainerSnapshot",
    "DeferredRef",
    "DeviceRef",
    "DtypeRef",
    "EdgeUseKind",
    "edge_use_kind",
    "FireResult",
    "FunctionCallRef",
    "FunctionEventInput",
    "FuncSite",
    "IdentityEntry",
    "InterventionState",
    "InterventionTemplateRef",
    "is_control_edge_use",
    "is_value_edge_use",
    "GradFnDiscovered",
    "GradFnFired",
    "LiveIndex",
    "LiveIndexWindowError",
    "MLXValueUnavailableError",
    "ModuleEnterEvent",
    "ModuleExitEvent",
    "ModuleFrame",
    "ModulePrepEvent",
    "ModelSite",
    "ModuleSite",
    "OpEvent",
    "OpEventKind",
    "OpGradObserved",
    "OutputRef",
    "OutputVersionEvent",
    "ParamGradObserved",
    "BackwardCoverageGap",
    "InterventionAppliedEvent",
    "ParamRef",
    "ParentEdge",
    "PreHookProvenanceEvent",
    "Phase",
    "RecordContext",
    "ReservedLabel",
    "Role",
    "WalkResult",
    "walk_container",
    "TensorRef",
    "LEGACY_TRACE_BUILD_STATE_KEYS",
    "ModuleCaptureWorkspace",
    "RawGraphWorkspace",
    "WrapperRuntimeWorkspace",
    "_DEFERRED_VALUE",
    "coerce_deferred_value",
    "is_deferred_value",
    "register_live_event",
]
