"""Semantic facet views for TorchLens records."""

from . import patching as patching, recipes as recipes
from .coverage import FacetCoverageReport, ModuleCoverageRow, facet_coverage
from .facets import (
    AttentionHeadView,
    Facet,
    FacetCapabilityFlags,
    FacetMenuItem,
    FacetRecipe,
    FacetRegistrySnapshot,
    FacetSpec,
    FacetView,
    MissingFacet,
    MissingFacetError,
    MissingGradient,
    TransformPrimitive,
    enable_transformerlens_aliases,
    info,
    list,
    register,
    reset,
    snapshot,
    transformer_lens_aliases_enabled,
    using,
)
from .logit_lens import (
    LogitLensEntry,
    LogitLensError,
    LogitLensResult,
    logit_lens,
)

__all__ = [
    "AttentionHeadView",
    "Facet",
    "FacetCapabilityFlags",
    "FacetMenuItem",
    "FacetRecipe",
    "FacetRegistrySnapshot",
    "FacetSpec",
    "FacetCoverageReport",
    "FacetView",
    "LogitLensEntry",
    "LogitLensError",
    "LogitLensResult",
    "logit_lens",
    "MissingFacetError",
    "MissingFacet",
    "ModuleCoverageRow",
    "facet_coverage",
    "MissingGradient",
    "TransformPrimitive",
    "enable_transformerlens_aliases",
    "info",
    "list",
    "register",
    "reset",
    "snapshot",
    "patching",
    "transformer_lens_aliases_enabled",
    "using",
]
