"""Layer mirror-field spec table and stored-state order (pure schema data).

Split out of ``layer.py`` under the R43 file-size ratchet. The mirror table
maps each public Layer field to its source Op field plus the exact
normalization the former copy-everything ``__init__`` applied at copy time;
the state order is the frozen ``__dict__`` insertion order every golden was
frozen against.
"""

from typing import Any

from ..quantities import Bytes, as_bytes, as_flops


def _as_total_param_memory(value: Any) -> Bytes:
    """Normalize ``Op.param_memory`` into the Layer total (``Bytes``)."""

    return Bytes(value or 0)


#: Mirror field table: public Layer field -> (source Op field, normalizer).
#: Entries with a ``None`` normalizer return the op's value unchanged (the
#: former ``__init__`` copies were plain reference copies for these).
_LAYER_MIRROR_SPEC: dict[str, tuple[str, Any]] = {
    **{
        name: (name, None)
        for name in (
            "layer_label",
            "layer_label_short",
            "layer_type",
            "type_index",
            "step_index",
            "ordinal_index",
            "raw_index",
            "num_passes",
            "func",
            "func_name",
            "func_qualname",
            "is_inplace",
            "grad_fn_class_name",
            "grad_fn_class_qualname",
            "grad_fn_object_id",
            "grad_fn_handle",
            "grad_fn",
            "arg_names",
            "num_args_total",
            "num_pos_args",
            "num_kwargs",
            "in_multi_output",
            "multi_output_index",
            "multi_output_name",
            "shape",
            "transformed_out_shape",
            "dtype",
            "dtype_ref",
            "transformed_out_dtype",
            "device_ref",
            "backend_address",
            "resolver_status",
            "num_autograd_tensors",
            "output_device",
            "visualizer_path",
            "activation_transform",
            "intervention_replaced",
            "detach_saved_activations",
            "save_grads",
            "transformed_grad_shape",
            "transformed_grad_dtype",
            "_param_barcodes",
            "_param_logs",
            "param_shapes",
            "num_params",
            "num_params_trainable",
            "num_params_frozen",
            "func_config",
            "equivalence_class",
            "is_input",
            "input_was_parameter",
            "is_output",
            "is_final_output",
            "is_buffer",
            "address",
            "buffer_source",
            "buffer_write_kind",
            "buffer_value_changed",
            "buffer_replay_validated",
            "buffer_source_func_name",
            "is_internal_source",
            "is_internal_sink",
            "is_terminal_bool",
            "is_scalar_bool",
            "bool_value",
            "in_conditionals",
            "terminal_bool_for",
            "module",
            "modules",
            "output_of_modules",
            "output_of_module_calls",
            "conditional_entry_children",
            "conditional_then_children",
            "conditional_elif_children",
            "conditional_else_children",
            "has_input_ancestor",
            "io_role",
            "buffer_pass",
            "is_atomic_module",
        )
    },
    "activation_memory": ("activation_memory", as_bytes),
    "transformed_activation_memory": ("transformed_activation_memory", as_bytes),
    "autograd_memory": ("autograd_memory", as_bytes),
    "total_autograd_memory": ("autograd_memory", as_bytes),
    "transformed_gradient_memory": ("transformed_gradient_memory", as_bytes),
    "flops_forward": ("flops_forward", as_flops),
    "flops_backward": ("flops_backward", as_flops),
    "total_param_memory": ("param_memory", _as_total_param_memory),
}

#: Complete stored-state name order: the exact ``__dict__`` insertion order of
#: the former copy-everything ``__init__`` (the pickle/state key order every
#: golden was frozen against). Mirror fields resolve through the descriptors;
#: the handful of genuinely stored fields read from ``__dict__``.
_LAYER_STATE_ORDER: tuple[str, ...] = (
    "layer_label",
    "layer_label_short",
    "layer_type",
    "type_index",
    "step_index",
    "ordinal_index",
    "raw_index",
    "num_passes",
    "_source_trace_ref",
    "func",
    "func_name",
    "func_qualname",
    "is_inplace",
    "grad_fn_class_name",
    "grad_fn_class_qualname",
    "grad_fn_object_id",
    "grad_fn_handle",
    "grad_fn",
    "arg_names",
    "num_args_total",
    "num_pos_args",
    "num_kwargs",
    "in_multi_output",
    "multi_output_index",
    "multi_output_name",
    "shape",
    "transformed_out_shape",
    "dtype",
    "dtype_ref",
    "transformed_out_dtype",
    "device_ref",
    "backend_address",
    "resolver_status",
    "activation_memory",
    "transformed_activation_memory",
    "autograd_memory",
    "total_autograd_memory",
    "num_autograd_tensors",
    "output_device",
    "visualizer_path",
    "activation_transform",
    "annotations",
    "intervention_replaced",
    "detach_saved_activations",
    "save_grads",
    "transformed_grad_shape",
    "transformed_grad_dtype",
    "transformed_gradient_memory",
    "flops_forward",
    "flops_backward",
    "_param_barcodes",
    "_param_logs",
    "param_shapes",
    "num_params",
    "num_params_trainable",
    "num_params_frozen",
    "total_param_memory",
    "func_config",
    "equivalence_class",
    "equivalent_ops",
    "is_input",
    "input_was_parameter",
    "is_output",
    "is_final_output",
    "is_buffer",
    "address",
    "buffer_source",
    "buffer_write_kind",
    "buffer_value_changed",
    "buffer_replay_validated",
    "buffer_source_func_name",
    "is_internal_source",
    "is_internal_sink",
    "is_terminal_bool",
    "is_scalar_bool",
    "bool_value",
    "in_conditionals",
    "terminal_bool_for",
    "_is_in_conditional_body",
    "conditional_role_stacks",
    "conditional_branch_stack_ops",
    "conditional_arm_children",
    "module",
    "modules",
    "output_of_modules",
    "output_of_module_calls",
    "conditional_entry_children",
    "conditional_then_children",
    "conditional_elif_children",
    "conditional_else_children",
    "has_input_ancestor",
    "io_role",
    "buffer_pass",
    "is_atomic_module",
    "ops",
    "call_labels",
)

_LAYER_STATE_ORDER_SET = frozenset(_LAYER_STATE_ORDER)
