"""Declared Trace field-to-component ownership map (M10 decomposition).

Every field in ``Trace.FIELD_POLICY`` (declared FIELD_ORDER surface plus
portable/runtime internals) is owned by exactly ONE lifecycle component of
the decomposed Trace (docs/reference/trace_core_design.md section 3.7).
A new Trace field must be added here with an owner, or the lockstep test
fails — the ratchet that keeps the god object from regrowing.

Components: header (identity/lifecycle), capture_config (capture-time
options snapshot), graph (the semantic TraceCore plane, incl. backward),
witness (honesty diagnostics), source_metadata (model source facts),
totals (aggregate counts/memory/timing), runnable (RunnableTraceState),
session (non-portable runtime, caches, append/intervention state, build
workspaces).
"""

from __future__ import annotations

TRACE_COMPONENT_VOCABULARY = frozenset(
    {
        "header",
        "capture_config",
        "graph",
        "witness",
        "source_metadata",
        "totals",
        "runnable",
        "session",
    }
)

TRACE_FIELD_OWNERSHIP: dict[str, str] = {
    "trace_label": "header",
    "model_class_name": "header",
    "model_label": "header",
    "tlspec_version": "header",
    "_tracing_finished": "header",
    "backend": "header",
    "backend_runtime_config": "header",
    "backend_runtime_device_summary": "header",
    "backend_runtime_version": "header",
    "module_identity_mode": "header",
    "param_source": "header",
    "derived_grads": "graph",
    # Union additions (2026-08-13 grind): fields declared by the G2/F3a/B1-04
    # fixes now carry owners. Semantic-output scratch + predicate keys are
    # session-lifetime; validation side channels are session; bundle-source
    # provenance rides source_metadata.
    "_output_head": "session",
    "_output_style": "session",
    "_output_tokenizer": "session",
    "_semantic_output_metadata": "session",
    "_last_validation_failure": "session",
    "_validation_diagnostics": "session",
    "_retain_layers_to_save_output_parents": "session",
    "_tl_predicate_intervention_spec_keys": "session",
    "_tl_predicate_intervention_target_keys": "session",
    "_source_bundle_manifest_sha256": "source_metadata",
    "_source_bundle_path": "source_metadata",
    "capture_mode": "header",
    "_runnable": "runnable",
    "_fast_run_session": "graph",
    "escape_detector_mode": "witness",
    "escape_detector_verified": "witness",
    "escape_diagnostics": "witness",
    "escape_detector_event_count": "witness",
    "escape_detector_callback_ns": "witness",
    "escape_detector_backward_coverage": "witness",
    "completeness_witness_mode": "witness",
    "completeness_witness_verified": "witness",
    "completeness_diagnostics": "witness",
    "completeness_decompositions": "witness",
    "completeness_witness_event_count": "witness",
    "completeness_witness_accounted_count": "witness",
    "completeness_witness_expected_opaque_count": "witness",
    "completeness_witness_unaccounted_count": "witness",
    "completeness_witness_callback_ns": "witness",
    "capture_verified": "witness",
    "capture_verification_reason": "witness",
    "rescue_rerun": "witness",
    "capture_owner_thread_id": "witness",
    "capture_owner_thread_qualified": "witness",
    "capture_thread_count_start": "witness",
    "capture_thread_count_end": "witness",
    "capture_thread_activity_detected": "witness",
    "capture_guard_passes": "witness",
    "halted": "witness",
    "halt_reason": "witness",
    "halt_frontier": "witness",
    "_capture_outcome": "witness",
    "_capture_phase": "session",
    "_settlement_ops_committed": "session",
    "_stop_requested": "session",
    "_layers_logged": "capture_config",
    "_layers_saved": "capture_config",
    "keep_orphans": "capture_config",
    "intervention_ready": "capture_config",
    "save_arg_templates": "capture_config",
    "raw_input": "graph",
    "input_preprocessor": "capture_config",
    "_transform": "capture_config",
    "transform_repr": "capture_config",
    "save_raw_input": "capture_config",
    "batch_render": "capture_config",
    "raw_output": "graph",
    "decoded_output": "graph",
    "output_postprocessor": "capture_config",
    "output_id2label": "capture_config",
    "output_num_classes": "capture_config",
    "_output_transform": "capture_config",
    "save_raw_output": "capture_config",
    "layer_visualizers": "capture_config",
    "save_visualizations": "capture_config",
    "_visualizer_dir": "capture_config",
    "random_seed": "capture_config",
    "detach_saved_activations": "capture_config",
    "output_device": "capture_config",
    "backward_ready": "capture_config",
    "inference_only": "capture_config",
    "chunked_forward": "capture_config",
    "module_filter": "capture_config",
    "emit_nvtx": "capture_config",
    "raise_on_nan": "capture_config",
    "annotations": "graph",
    "observer_spans": "graph",
    "manual_tensor_connections": "graph",
    "forward_source_file": "source_metadata",
    "forward_source_line": "source_metadata",
    "class_source_file": "source_metadata",
    "class_source_line": "source_metadata",
    "init_source_file": "source_metadata",
    "init_source_line": "source_metadata",
    "class_docstring": "source_metadata",
    "init_signature": "source_metadata",
    "init_docstring": "source_metadata",
    "forward_signature": "source_metadata",
    "forward_docstring": "source_metadata",
    "code_context": "source_metadata",
    "capture_cache_hit": "graph",
    "capture_cache_key": "graph",
    "capture_cache_path": "graph",
    "facet_registry_snapshot": "graph",
    "recording_kept": "graph",
    "_out_dedup_mode": "graph",
    "_out_identity_cache": "graph",
    "_out_hash_cache": "graph",
    "_code_context_cache": "graph",
    "_replay_arg_version_data_complete": "witness",
    "save_arg_values": "capture_config",
    "num_context_lines": "capture_config",
    "save_grads": "capture_config",
    "capture_tensor_grad_hooks": "capture_config",
    "_grad_op_nums_to_save": "capture_config",
    "grad_transform": "capture_config",
    "grad_transform_repr": "capture_config",
    "save_raw_gradients": "capture_config",
    "save_code_context": "capture_config",
    "save_rng_states": "capture_config",
    "recurrence_detection": "capture_config",
    "verbose": "capture_config",
    "profile_enabled": "capture_config",
    "has_gradients": "totals",
    "activation_transform": "capture_config",
    "_activation_transform_repr": "capture_config",
    "save_raw_activations": "capture_config",
    "save_mode": "capture_config",
    "input_annotations": "graph",
    "_source_code_blob": "source_metadata",
    "_source_model_ref": "source_metadata",
    "parent_run": "graph",
    "model_object_id": "source_metadata",
    "model_class_qualname": "source_metadata",
    "param_hash_quick": "source_metadata",
    "param_hash_full": "source_metadata",
    "input_object_id": "source_metadata",
    "input_signature_hash": "source_metadata",
    "mark_layer_depths": "capture_config",
    "graph_shape_hash": "header",
    "_intervention_spec": "graph",
    "state_history": "graph",
    "last_run": "graph",
    "append_history": "graph",
    "_has_direct_writes": "graph",
    "_warned_direct_write": "graph",
    "_warned_mutate_in_place": "graph",
    "_spec_revision": "graph",
    "_out_recipe_revision": "graph",
    "_append_sequence_id": "graph",
    "_last_hook_handle_ids": "graph",
    "state": "header",
    "is_appended": "header",
    "relationship_evidence": "graph",
    "replay_frontier": "graph",
    "layer_list": "graph",
    "layer_dict_main_keys": "graph",
    "layer_dict_all_keys": "graph",
    "layer_logs": "graph",
    "layer_labels": "graph",
    "op_labels": "graph",
    "layer_num_calls": "graph",
    "by_pass": "graph",
    "_layer_nums_to_save": "capture_config",
    "num_ops": "totals",
    "num_modules": "totals",
    "_raw_to_final_layer_labels": "graph",
    "_raw_to_final_parent_layer_labels": "graph",
    "_raw_to_final_op_labels": "graph",
    "_final_to_raw_layer_labels": "graph",
    "_lookup_keys_to_layer_num_dict": "graph",
    "_layer_num_to_lookup_keys_dict": "graph",
    "_ambiguous_lookup_keys": "graph",
    "input_layers": "graph",
    "output_layers": "graph",
    "input_structure": "graph",
    "_containers": "graph",
    "_annotation_blobs": "graph",
    "buffer_layers": "graph",
    "buffer_num_calls": "graph",
    "_buffer_persistence": "graph",
    "internal_source_ops": "graph",
    "internal_sink_ops": "graph",
    "internally_terminated_bool_ops": "graph",
    "conditional_branch_edges": "graph",
    "conditional_records": "graph",
    "conditional_arm_entry_edges": "graph",
    "conditional_edge_call_indices": "graph",
    "conditionals": "graph",
    "layers_with_params": "graph",
    "op_equivalence_classes": "graph",
    "_orphan_labels": "graph",
    "_orphan_logs": "graph",
    "orphan_records": "graph",
    "total_activation_memory": "totals",
    "total_gradient_memory": "totals",
    "total_backward_memory": "totals",
    "total_autograd_memory": "totals",
    "num_saved_ops": "totals",
    "saved_activation_memory": "totals",
    "saved_gradient_memory": "totals",
    "num_saved_layers": "totals",
    "num_saved_module_calls": "totals",
    "num_saved_grad_fns": "totals",
    "num_saved_grad_fn_calls": "totals",
    "param_logs": "graph",
    "num_param_tensors": "totals",
    "num_layers_with_params": "totals",
    "num_params": "totals",
    "num_params_trainable": "totals",
    "num_params_frozen": "totals",
    "total_param_memory": "totals",
    "total_param_gradient_memory": "totals",
    "forward_peak_memory": "totals",
    "forward_memory_backend": "totals",
    "capture_start_time": "totals",
    "capture_end_time": "totals",
    "_phase_timings": "totals",
    "setup_duration": "totals",
    "forward_duration": "totals",
    "cleanup_duration": "totals",
    "func_calls_duration": "totals",
    "has_backward_pass": "totals",
    "grad_fn_logs": "graph",
    "grad_fn_order": "graph",
    "backward_pass_logs": "graph",
    "_grad_fn_param_refs": "graph",
    "backward_root_grad_fn_object_ids": "graph",
    "backward_durations": "totals",
    "num_backward_passes": "totals",
    "backward_peak_memory": "totals",
    "backward_memory_backend": "totals",
    "_cooked_from": "header",
    "_paddle_capture_depth": "session",
    "_paddle_op_captures": "session",
    "_paddle_alias_annotations": "session",
    "_paddle_capture_gap_markers": "session",
    "_tf_unresolved_producers": "session",
    "_tf_init_op_labels": "session",
    "_tf_op_captures": "session",
    "_tf_validation_result": "session",
    "_tl_save_selector_fire_count": "session",
    "_module_call_accessor": "graph",
    "_receptive_field_solution": "session",
    "_rf_source_solutions": "session",
    "_rf_target_solutions": "session",
    "_optimizer": "session",
    "measure_python_peak_memory": "capture_config",
    "distributed_witness": "capture_config",
    "save_budget": "capture_config",
    "_warned_nonfinite_check_unavailable": "session",
    "_predicate_save_options": "session",
    "_predicate_history_size": "session",
    "_predicate_history": "session",
    "_predicate_lookback": "session",
    "_predicate_lookback_payload_policy": "session",
    "_capture_config": "capture_config",
    "_stop_directive": "session",
    "_halt_returns_partial_trace": "session",
    "_predicate_save_decisions": "session",
    "_predicate_current_contexts": "session",
    "_predicate_lookback_candidates": "session",
    "_postprocessing_active": "session",
    "_raw_transform_escape_detected": "witness",
    "_raw_dynamo_region_detected": "witness",
    "_raw_event_shape_hash": "witness",
    "_output_container_specs_by_raw_label": "graph",
    "_buffer_accessor": "graph",
    "_buffer_write_tracker": "graph",
    "_param_storage_addresses": "graph",
    "_buffer_initial_values": "graph",
    "_saved_grad_labels": "graph",
    "ops_with_params": "graph",
    "_pending_live_fire_records": "session",
    "_module_logs": "graph",
    "_param_logs_by_module": "graph",
    "_raw_graph_ws": "session",
    "_module_capture_ws": "session",
    "_wrapper_runtime_ws": "session",
    "_trace_core": "graph",
    "_pre_forward_rng_states": "session",
    "_buffer_storage_addresses": "graph",
    "_mlx_saved_payloads": "session",
    "_mlx_capture_depth": "session",
    "_out_writer": "session",
    "_save_budget_accountant": "session",
    "_keep_outs_in_memory": "session",
    "_grad_stream_retain_in_memory": "session",
    "_defer_streaming_bundle_finalization": "session",
    "_out_sink": "session",
    "_orphan_pruned_func_call_ids": "graph",
    "_capture_parent_edge_truth": "graph",
    "_capture_events": "session",
    "_capture_session": "session",
    "_tl_backward_hooked_tensor_keys": "session",
    "_tl_grad_hook_owner_by_label": "session",
    "_tl_rf_probe_active": "session",
    "_active_backward_pass_index": "graph",
    "_backward_roots_by_pass": "graph",
    "_backward_projection_event_count": "graph",
    "_backward_projection_revision": "graph",
    "_backward_projection_fold_state": "graph",
    "_implicit_backward_pass_open": "graph",
    "_warned_implicit_backward_pass": "session",
    "_tl_backward_triggers_disarmed": "session",
    "_grad_fn_param_refs_by_object_id": "graph",
    "_param_log_by_pid": "graph",
    "_session_param_inventory": "session",
    "_session_buffer_inventory": "session",
    "_session_buffer_identity": "session",
    "_backward_gradfn_refs": "graph",
}
